### ISSUE TITLE
Cannot find function Export-NAVAppTableData

### ISSUE THREAD

**Issue by mmenninghaus** [microsoft/navcontainerhelper#2906]
**Describe the issue**
We used to build .app-files including certain configurations an settings in our pipeline. Therefore we used the function *Export-NAVAppTableData*. Unfortunately it is nowhere to find, even not in the git history. I am 100% sure that it has been a part of the navcontainerhelper for quite a long time and actively used it a couple of weeks ago.

**Additional context**
- cannot find the desired script in the git history
- used to work with version 4.0.4

**Comment by mmenninghaus** [comment]
It is not a containerhelper script but a function from aNAV-module
Problem is that it does not seem to ship with BC 21 - will need to find a workaround - not containerhelper related

**Comment by mmenninghaus** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.tools/export-navapptabledata?view=businesscentral-ps-21
